dist: trusty
sudo: required

services:
  - docker

language: node_js
node_js:
  - "node"
  - "8"

before_install:
  - npm i -g npm@5.6.0

script:
  - npm run lint

after_success:
  - docker build -t $DOCKER_USERNAME/hubot-natural:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/hubot-natural
